# Site
repository: seunggeunjo/seunggeunjo.github.io
# favicon: images/favicon.ico

# Personal info
name: 조승근
title: 소프트웨어 엔지니어
email: geun9544@gmail.com
# website: https://example.com

# Social links
# twitter_username: seunggeunjo
github_username:  seunggeunjo
# dribbble_username: jekyll
# facebook_username: seunggeunjo
# flickr_username: jekyll
# linkedin_username: seunggeunjo
# pinterest_username: jekyll
# youtube_username: channel_id

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  소프트웨어 엔지니어 조승근입니다.<br/>
  여기에 자기소개를 작성해주세요.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  여기에 추가 정보를 작성해주세요.
   - 프로젝트, 발표, 기고 등을 추가할 수 있습니다.
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
